run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - unconvert
    - misspell
    - noctx

linters-settings:
  errcheck:
    check-type-assertions: true
